<?php

/**
 * @file
 * Install file for module.
 */

use OpenSpout\Writer\XLSX\Writer;

/**
 * Implements hook_requirements().
 */
function xls_serialization_open_spout_requirements($phase) {
  $requirements = [];
  if ($phase === 'install') {
    if (!class_exists(Writer::class)) {
      $requirements['xls_serialization_open_spout'] = [
        'description' => t('Serialization (Excel using OpenSpout library) requires the OpenSpout\OpenSpout library.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }
  return $requirements;
}
