<?php

/**
 * @file
 * Module file for Layout Builder Restrictions by Region.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\layout_builder_restrictions_by_region\Hook\LayoutBuilderRestrictionsByRegionHooks;

/**
 * Implements hook_form_FORM_ID_alter() for the entity view display edit form.
 */
#[LegacyHook]
function layout_builder_restrictions_by_region_form_entity_view_display_edit_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  \Drupal::service(LayoutBuilderRestrictionsByRegionHooks::class)->formEntityViewDisplayEditFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter() for the general config form.
 */
#[LegacyHook]
function layout_builder_restrictions_by_region_form_restriction_plugin_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(LayoutBuilderRestrictionsByRegionHooks::class)->formRestrictionPluginConfigFormAlter($form, $form_state, $form_id);
}
