<?php

/**
 * @file
 * Install hooks for this module.
 */

use JamesHeinrich\GetID3\GetID3;

/**
 * Implements hook_requirements().
 */
function views_rss_media_getid3_requirements($phase) {
  $requirements = [];

  if (!class_exists(GetID3::class)) {
    $requirements['views_rss_media_getid3'] = [
      'title' => t('Advanced Views RSS Feed: Media getID3'),
      'description' => t('Advanced Views RSS Feed: Media getID3 requires the getID3 library, see the README.md file included in this module for details.'),
      'severity' => REQUIREMENT_ERROR,
    ];
  }

  return $requirements;
}
