<?php

/**
 * @file
 * Register D7's unmanaged public files as D10 file entities (and media).
 *
 * D7 accumulated ~24k files that were uploaded outside Drupal (IMCE, FTP,
 * direct copies) and so never had a {file_managed} row. No migration touches
 * them: they are not in the file migrations, they cannot be referenced by a
 * media field, and nothing copies them to a new environment. They are linked
 * directly from body HTML -- 8k of them are referenced from D10 content today
 * -- so a missing copy is a broken download or image on a live page.
 *
 * scripts-dev/stage_unmanaged_files.sh copies the files; this registers them:
 *   - a permanent File entity for every file, so the tree is tracked and
 *     travels with the site;
 *   - a Media entity for the ones referenced from D10 content, so editors can
 *     find and reuse them in the library. Pass --all-media to create media for
 *     every file instead.
 *
 * Both lists are read from scripts-dev/unmanaged/ (generated by the staging
 * script). Idempotent: existing files/media are matched by URI and skipped.
 *
 * Usage: drush scr scripts-dev/register_unmanaged_files.php
 *        drush scr scripts-dev/register_unmanaged_files.php -- --all-media
 */

use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

$all_media = in_array('--all-media', $extra ?? [], TRUE) || in_array('--all-media', $_SERVER['argv'] ?? [], TRUE);
$dir = DRUPAL_ROOT . '/../scripts-dev/unmanaged/';
$list = $dir . 'all.txt';
$referenced_list = $dir . 'referenced.txt';
if (!file_exists($list)) {
  print "Missing $list — run scripts-dev/stage_unmanaged_files.sh first.\n";
  return;
}
$files = array_filter(array_map('trim', file($list)));
$referenced = file_exists($referenced_list)
  ? array_flip(array_filter(array_map('trim', file($referenced_list))))
  : [];

$fs = \Drupal::service('file_system');
$guesser = \Drupal::service('file.mime_type.guesser');
$db = \Drupal::database();
$existing = [];
foreach ($db->query("SELECT uri, fid FROM {file_managed} WHERE uri LIKE 'public://%'") as $row) {
  $existing[$row->uri] = (int) $row->fid;
}
$media_by_fid = [];
foreach (['field_media_file', 'field_media_image'] as $field) {
  $table = 'media__' . $field;
  if ($db->schema()->tableExists($table)) {
    foreach ($db->query("SELECT {$field}_target_id AS fid, entity_id FROM {" . $table . "}") as $row) {
      $media_by_fid[(int) $row->fid] = (int) $row->entity_id;
    }
  }
}

// Media bundle + source field by mime.
$bundle_for = function (string $mime): array {
  if (str_starts_with($mime, 'image/')) {
    return ['image', 'field_media_image'];
  }
  if (str_starts_with($mime, 'audio/')) {
    return ['audio', 'field_media_file'];
  }
  if (str_starts_with($mime, 'video/')) {
    return ['local_video', 'field_media_file'];
  }
  return ['document', 'field_media_file'];
};

$made_files = $skipped_files = $made_media = $skipped_media = $absent = 0;
$i = 0;
foreach ($files as $rel) {
  $i++;
  $uri = 'public://' . $rel;
  $path = $fs->realpath($uri);
  if (!$path || !file_exists($path)) {
    $absent++;
    continue;
  }
  $fid = $existing[$uri] ?? NULL;
  if ($fid === NULL) {
    $mime = $guesser->guessMimeType($uri);
    $file = File::create([
      'uri' => $uri,
      'filename' => $fs->basename($uri),
      'filemime' => $mime,
      'filesize' => filesize($path),
      'status' => 1,
      'uid' => 1,
    ]);
    $file->save();
    $fid = (int) $file->id();
    $existing[$uri] = $fid;
    $made_files++;
  }
  else {
    $skipped_files++;
    $file = File::load($fid);
    $mime = $file ? $file->getMimeType() : 'application/octet-stream';
  }

  if (!$all_media && !isset($referenced[$rel])) {
    continue;
  }
  if (isset($media_by_fid[$fid])) {
    $skipped_media++;
    continue;
  }
  [$bundle, $field] = $bundle_for($mime ?? 'application/octet-stream');
  $name = $fs->basename($uri);
  $values = [
    'bundle' => $bundle,
    'name' => mb_substr($name, 0, 255),
    'uid' => 1,
    'status' => 1,
  ];
  $values[$field] = $bundle === 'image'
    ? ['target_id' => $fid, 'alt' => '']
    : ['target_id' => $fid];
  $media = Media::create($values);
  $media->save();
  $media_by_fid[$fid] = (int) $media->id();
  $made_media++;

  if ($i % 2000 === 0) {
    printf("  ... %d/%d (files +%d, media +%d)\n", $i, count($files), $made_files, $made_media);
  }
}
printf(
  "Files: %d created, %d already managed, %d absent on disk. Media: %d created, %d already present.\n",
  $made_files, $skipped_files, $absent, $made_media, $skipped_media
);
