<?php

/**
 * @file
 * Contains layout_builder_reorder module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\layout_builder_reorder\Hook\LayoutBuilderReorderHooks;

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function layout_builder_reorder_element_info_alter(array &$types): void {
  \Drupal::service(LayoutBuilderReorderHooks::class)->elementInfoAlter($types);
}
