<?php

declare(strict_types=1);

namespace Drupal\Tests\ui_patterns\Kernel\Source;

use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\Tests\ui_patterns\Kernel\SourcePluginsTestBase;
use Drupal\ui_patterns\Plugin\UiPatterns\Source\MenuSource;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Test MenuSource.
 *
 * @internal
 */
#[CoversClass(MenuSource::class)]
#[Group('ui_patterns')]
#[RunTestsInSeparateProcesses]
final class MenuSourceTest extends SourcePluginsTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = ['link', 'menu_link_content', 'menu_ui'];

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    // @todo Change the autogenerated stub
    parent::setUp();
    $this->installEntitySchema('menu_link_content');
    $this->installEntitySchema('user');
    $link = MenuLinkContent::create([
      'menu_name' => 'main',
      'link' => [['uri' => 'internal:/example-path']],
      'weight' => 5,
    ]);
    $link->save();
  }

  /**
   * Test MenuSource Plugin.
   */
  public function testPlugin(): void {
    $testData = self::loadTestDataFixture(__DIR__ . '/../../../fixtures/menu_tests.yml');
    $testSet = $testData->getTestSet('menu_1');
    $testSet['output'] = [
      'props' => [
        'links' => [
          'closure' => function ($output_of_source) {
            $this->assertNotNull($output_of_source);
            $this->assertTrue(\is_array($output_of_source));
            $this->assertTrue(\count($output_of_source) > 0);
            $this->assertTrue(\is_array($output_of_source[0]));
            $this->assertEquals($output_of_source[0]['url'], '/example-path');
          },
        ],
      ],
    ];
    $this->runSourcePluginTest($testSet);
  }

  /**
   * A menu link title with a phishing anchor stays an untrusted string.
   *
   * A MenuLinkContent title (a plain-text field, no text format) holds a
   * phishing <a>. The source returns it as a plain string — untrusted, so
   * Twig autoescapes it at render (see MenuSourceRenderTest for the
   * rendered assertion).
   */
  public function testPhishingTitleIsUntrusted(): void {
    MenuLinkContent::create([
      'menu_name' => 'main',
      'title' => '<a href="https://phishing.example/">Sign in</a>',
      'link' => [['uri' => 'internal:/user/login']],
      'weight' => 1,
    ])->save();

    $testData = self::loadTestDataFixture(__DIR__ . '/../../../fixtures/menu_tests.yml');
    $testSet = $testData->getTestSet('menu_1');
    $testSet['output'] = [
      'props' => [
        'links' => [
          'closure' => function ($output_of_source) {
            $this->assertIsArray($output_of_source);
            $phishing_item = NULL;
            foreach ($output_of_source as $item) {
              if (!is_array($item) || !isset($item['url'])) {
                continue;
              }
              if ($item['url'] === '/user/login') {
                $phishing_item = $item;
                break;
              }
            }
            $this->assertNotNull($phishing_item, 'Phishing menu link was not produced by the source.');
            // assertSame on the raw string also proves the title is not
            // wrapped in Markup, so it stays untrusted for Twig.
            $this->assertSame('<a href="https://phishing.example/">Sign in</a>', $phishing_item['title']);
          },
        ],
      ],
    ];
    $this->runSourcePluginTest($testSet);
  }

}
