_core:
  default_config_hash: 4ecPXvfCsotFyuUYiSemqVkVtbtIJawEGaynUB4me_s
pdf_using_mpdf:
  pdf_filename: '[site:name]-[current-date:html_datetime]'
  pdf_save_option: '0'
  pdf_set_title: ''
  pdf_set_author: ''
  pdf_set_subject: ''
  pdf_set_creator: ''
  margin_top: '15'
  margin_right: '10'
  margin_bottom: '10'
  margin_left: '10'
  margin_header: '9'
  margin_footer: '9'
  pdf_font_size: '12'
  pdf_default_font: dejavusans
  pdf_page_size: A4
  dpi: '96'
  img_dpi: '96'
  orientation: P
  watermark_option: '0'
  watermark_opacity: '0.1'
  pdf_watermark_text: ''
  watermark_image: {  }
  pdf_header: ''
  pdf_footer: ''
  pdf_css_file: ''
  pdf_password: ''
